apiVersion: v1
kind: Service
metadata:
  name: free5gc-upf-svc-2
spec:
  selector:
    app: free5gc-upf-2
  type: NodePort
  clusterIP: 10.96.100.11
  ports:
    - name: pfcp
      protocol: UDP
      port: 8805
      nodePort: 31806
    - name: sbi
      port: 29518
      protocol: TCP
      nodePort: 32519
    - name: gtp
      protocol: UDP
      port: 2152
      nodePort: 32153
