apiVersion: v1
kind: Service
metadata:
  name: free5gc-upf-svc-3
spec:
  selector:
    app: free5gc-upf-3
  type: NodePort
  clusterIP: 10.96.100.12
  ports:
    - name: pfcp
      protocol: UDP
      port: 8805
      nodePort: 31807
    - name: sbi
      port: 29518
      protocol: TCP
      nodePort: 32520
    - name: gtp
      protocol: UDP
      port: 2152
      nodePort: 32154
