apiVersion: v1
kind: Pod
metadata:
  name: svr
spec:
  containers:
  - name: svr
    image: cturra/ntp
    ports:
      - containerPort: 123
        protocol: UDP

---

apiVersion: v1
kind: Pod
metadata:
  name: lb
spec:
  containers:
  - name: lb
    image: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: cli
spec:
  containers:
  - name: cli
    image: nginx
